apiVersion: v1
kind: Service
metadata:
    name: flask-change-service
spec:
    selector:
        app: change-app
    ports:
    - protocol: "TCP"
      port: 8080
      targetPort:8080
    type: LoadBalancer
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: change-app
spec:
    selector:
        matchLabels:
            app: change-app
    replicas: 3
    template:
        metadata:
            labels:
                app: change-app
        spec:
            containers:
            - name: flask_change
              image: flask_change:latest
              imagePullPolicy: Never
              ports:
              - containerPort: 8080